language: python
python: 
    - "3.7"
install:
    - pip install -r ml-service/ml-server/requirements.txt
    - cd frontend/view
    - npm install || true
    - cd ../..
script:
    - python -m pytest
    - cd frontend/view
    - npm run test
    - flake8 --extend-ignore=F401
